### ISSUE TITLE
Benedict: Radiant Blades

### ISSUE THREAD

**Issue by harrand** [harrand/Red-Nightmare#19]
Implement Benedict's base-ability: Radiant Blades

- Benedict should have two blades equipped by default
- Left-clicking causes Benedict to throw one of his blades to the target location.
- If Benedict has two blades prior to throwing, only one should be displayed on his sprite after throwing.
- If Benedict has already thrown both blades, Radiant Blades should be unavailable
- Benedict should be able to walk to his thrown blades to retrieve them.

**Comment by Harrand** [comment]
Note: Benedict will be an additional unlockable character. The default character is Akhara, who is the priority. For this reason this issue doesn't yet have a milestone
