### ISSUE TITLE
Bug: Flickering on Release

### ISSUE THREAD

**Issue by harrand** [harrand/Red-Nightmare#32]
OpenGL and Vulkan release both have flickering in their levels. Probably related to weather. Affects both snow and rain.

Haven't tried without weather effect yet

**Comment by Harrand** [comment]
Confirmed that this reproduces even without a weather effect. It looks like the OverlayID for weather effects somehow sometimes turns black.

Likely candidates:
- FPS in release is probably in the thousands, could be simple tearing, although i thought VK_PRESENT_MODE_MAILBOX_KHR prevented this? iirc vsync is not enabled on either build
- There is some kind of gpu sync issue with the effect renderers. afaik these do have RenderWait which sacrifices a huge amount of perf to guarantee no sync issues, but maybe it's still going pear-shaped anyway!
There's definitely no debug-only logic in the code triggering this, its a weird one.

**Comment by harrand** [comment]
This stopped reproing months ago, but I was too lazy to pin down when. Just pretend this never happened!
