### ISSUE TITLE
Powerup Request: Orb of the Underglacier

### ISSUE THREAD

**Issue by harrand** [harrand/Red-Nightmare#5]
**Powerup Name**
Orb of the Underglacier

**Description of the Powerup**
Qurai gifts you his glacial orb.

**Quality**
Yellow

**Which character is this available to?**
Akhara

**Explanation of how it works**
Orb of the Underglacier permanently replaces Akhara's default fireball with a frozen orb. The frozen orb is similar, but when dealing damage to low-health non-boss enemies it has a chance to freeze them, killing them instantly.

**Comment by Harrand** [comment]
The freezing effect on enemies is going to require some kind of way for an actor to die without playing its death animation but instead encasing it in a block of ice.

Game tech isn't really at that point yet, so this is being pushed to a future release
